version: '3.4'

services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication
    container_name: test-web-mvc
    build:
      context: .
      dockerfile: WebApplication/Dockerfile

  testapi:
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: testApi/Dockerfile